#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added
ARTIFACTS_DIR=/tmp/artifacts

fullname=$(find $ARTIFACTS_DIR -name spark-[0-9.]*-bin-hadoop[0-9.]*\.tgz)
bash -x $SCRIPT_DIR/check_for_download $fullname
cp $fullname /opt

pushd /opt
tar -zxf $(basename $fullname)
ln -s $(basename $fullname .tgz) spark
rm $(basename $fullname)
popd

/opt/sbt/bin/sbt

cp -r $ADDED_DIR/s2i/* $STI_SCRIPTS_PATH
cp -R $SCRIPT_DIR/s2i/sbt/plugins /tmp/.sbt/0.13
chmod a+x $STI_SCRIPTS_PATH/*
chown -R 185:0 $APP_ROOT && chmod a+rwX -R $APP_ROOT
chown -R 185:0 /opt/spark/conf && chmod g+rw -R /opt/spark/conf
chown -R 185:0 /opt/sbt/conf && chmod g+rw -R /opt/sbt/conf
chown -R 185:0 /tmp/.ivy2 && chmod g+rw -R /tmp/.ivy2
chown -R 185:0 /tmp/.sbt && chmod g+rw -R /tmp/.sbt
if [ -f /home/jboss ]; then
    chmod -R g+rwX /home/jboss
fi
