#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

mkdir -p /usr/local/s2i
cp -r $ADDED_DIR/s2i/* /usr/local/s2i

if [ -f /home/jboss ]; then
    chmod -R g+rwX /home/jboss
fi
