#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added
ARTIFACTS_DIR=/tmp/artifacts

mkdir -p $APP_ROOT/src && mkdir -p $APP_ROOT/etc
chown -R 185:0 $APP_ROOT && chmod a+rwX -R $APP_ROOT
cp $ADDED_DIR/utils/* $APP_ROOT/src
cp $ADDED_DIR/etc/* $APP_ROOT/etc

# Change the permissions on /etc/passwd so that anonymous user
# can be added to satisfy Spark
chgrp root /etc/passwd && chmod ug+rw /etc/passwd

# If there is a zero-length oshinko-cli tarball, find the verison in the
# name and download from github
fullname=$(find $ARTIFACTS_DIR -name oshinko_v[0-9.]*_linux_amd64\.tar\.gz)
if ! [ -s "$fullname" ]; then
    oshinko=$(basename $fullname)
    version=$(echo $oshinko | cut -d '_' -f2)
    wget https://github.com/radanalyticsio/oshinko-cli/releases/download/$version/$oshinko -O $fullname
fi
cp $fullname $APP_ROOT/src
pushd $APP_ROOT/src
tar -zxf $(basename $fullname)
mv oshinko_linux_amd64/oshinko oshinko
rm -rf oshinko_linux_amd64 $(basename $fullname)
popd

fullname=$(find $ARTIFACTS_DIR -name spark-[0-9.]*-bin-hadoop[0-9.]*\.tgz)
if ! [ -s "$fullname" ]; then
    spark=$(basename $fullname)
    version=$(echo $spark | cut -d '-' -f2)
    wget https://archive.apache.org/dist/spark/spark-$version/$spark -O $fullname
fi
cp $fullname /opt
pushd /opt
tar -zxf $(basename $fullname)
ln -s $(basename $fullname .tgz) spark
rm $(basename $fullname)
popd
cp $ADDED_DIR/spark-conf/* /opt/spark/conf/

TINI_VERSION=v0.16.1
wget -q https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -P /tmp
wget -q https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini.asc -P /tmp
cd /tmp
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0527A9B7 && gpg --verify /tmp/tini.asc
mv /tmp/tini /sbin/tini
chmod +x /sbin/tini

# Since the s2i generated images can be run as the driver/executor images
# in the kubernetes native scheduling case, /etc/passwd needs group permission
# to support the spark entry point user handling (radanalytics.io scripts
# use a shadow password file instead)
chgrp root /etc/passwd && chmod ug+rw /etc/passwd
chown -R 185:0 /opt/spark/conf && chmod g+rw -R /opt/spark/conf
