#!/bin/bash
set -e
shopt -s dotglob

# first run the original assemble script
/usr/libexec/s2i/assemble.orig

echo "---> Proceeding with customized assemble ..."

# If the root of the repo contains file called worker-requirements.txt, install them and bundle
# them together into big zip file that will be passed to spark-submit.

# note: the idea of worker-requirements.txt is to isolate those dependencies that
# are necessary only for spark workers, because not all the dependencies driver needs
# are also needed on the worker nodes
r_file="worker-requirements.txt"
if [ -f "$APP_ROOT/src/$r_file" ]; then
    pushd $APP_ROOT/src
    echo "---> Building worker-gen-dependencies.zip based on $r_file ..."
    pip install --upgrade pip
    pip install -t worker-gen-dependencies -r $r_file
    pushd worker-gen-dependencies
    zip -r ../worker-gen-dependencies.zip .
    export PYTHON_WORKER_DEPS=`readlink -f ../worker-gen-dependencies.zip`
    popd
    popd
fi

# set permissions for any installed artifacts
fix-permissions /opt/app-root
