#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added
ARTIFACTS_DIR=/tmp/artifacts

cp $ARTIFACTS_DIR/scala-2.11.8.tgz /opt
cp $ARTIFACTS_DIR/sbt-0.13.13.tgz /opt

pushd /opt
tar -zxf scala-2.11.8.tgz
ln -s scala-2.11.8 scala

tar -zxf sbt-0.13.13.tgz
ln -s sbt-launcher-packaging-0.13.13 sbt
popd

/opt/sbt/bin/sbt

mkdir -p /usr/local/s2i
cp -r $ADDED_DIR/s2i/* /usr/local/s2i
chmod a+x /usr/local/s2i/*
chown -R 185:0 $APP_ROOT && chmod a+rwX -R $APP_ROOT
chown -R 185:0 /opt/spark/conf && chmod g+rw -R /opt/spark/conf
chown -R 185:0 /opt/sbt/conf && chmod g+rw -R /opt/sbt/conf
chown -R 185:0 /tmp/.ivy2 && chmod g+rw -R /tmp/.ivy2
chown -R 185:0 /tmp/.sbt && chmod g+rw -R /tmp/.sbt
if [ -f /home/jboss ]; then
    chmod -R g+rwX /home/jboss
fi
