#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added
ARTIFACTS_DIR=/tmp/artifacts

/opt/sbt/bin/sbt exit

cp -r $ADDED_DIR/s2i/* $STI_SCRIPTS_PATH
cp -R $SCRIPT_DIR/s2i/sbt/plugins /tmp/.sbt/1.0

chown -R 185:0 /opt/sbt/conf && chmod g+rw -R /opt/sbt/conf
chown -R 185:0 /tmp/.ivy2 && chmod g+rw -R /tmp/.ivy2
chown -R 185:0 /tmp/.sbt && chmod g+rw -R /tmp/.sbt
if [ -f /home/jboss ]; then
    chmod -R g+rwX /home/jboss
fi
