#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added
ARTIFACTS_DIR=/tmp/artifacts

fullname=$(find $ARTIFACTS_DIR -name spark-[0-9.]*-bin-hadoop[0-9.]*\.tgz)
if ! [ -s "$fullname" ]; then
    spark=$(basename $fullname)
    version=$(echo $spark | cut -d '-' -f2)
    wget https://archive.apache.org/dist/spark/spark-$version/$spark -O $fullname
fi

# Make a place for spark to go (dupe what's done in common in case we're standalone)
if ! [ -d $SPARK_INSTALL ]; then
    mkdir -p $SPARK_INSTALL
    ln -sfn $SPARK_INSTALL/distro $SPARK_HOME
    chown 185:0 $SPARK_INSTALL && chmod g+rwx $SPARK_INSTALL
fi

pushd $SPARK_INSTALL
cp $fullname .
tar -zxf $(basename $fullname)
ln -s $(basename $fullname .tgz) distro
rm $(basename $fullname)
popd

# Search for the spark entrypoint file and copy it to $APP_ROOT/etc
entry=$(find $SPARK_INSTALL/$(basename $fullname .tgz)/kubernetes -name entrypoint.sh)
if [ -n "$entry" ]; then
    mkdir -p $APP_ROOT/etc
    cp $entry $APP_ROOT/etc

    # We have to patch the entrypoint to toggle error checking
    # around the uidentry check until for 2.3 (fix on the way)
    sed -i '/^uidentry/i set +e' $APP_ROOT/etc/$(basename $entry)
    sed -i '/^uidentry/a set -e' $APP_ROOT/etc/$(basename $entry)


    # We also want to get rid of the tini invocation
    sed -i "s@exec /sbin/tini -s --@exec@" $APP_ROOT/etc/$(basename $entry)
fi

cp $ADDED_DIR/spark-conf/* $SPARK_HOME/conf/
chown -R 185:0 $SPARK_HOME/conf && chmod g+rw -R $SPARK_HOME/conf
