#!/bin/bash

function del_dc() {
    set_defaults
    # If there are 2 args the second is a cluster name
    if [ "$#" -eq 1 ]; then
        run_app
    else
        run_app $2
    fi

    # Wait until a particular message is seen and the cluster dcs exist
    os::cmd::try_until_text 'oc logs dc/bob' "$1" $((5*minute))
    os::cmd::try_until_success 'oc get dc "$MASTER_DC"' $((2*minute))
    os::cmd::try_until_success 'oc get dc "$WORKER_DC"'

    # Delete the driver dc
    os::cmd::expect_success 'oc delete dc/bob'
    os::cmd::try_until_failure 'oc get dc/bob'

    # Check for the master and worker dcs, they should be gone and won't reappear
    os::cmd::try_until_failure 'oc get dc "$MASTER_DC"'
    os::cmd::try_until_failure 'oc get dc "$WORKER_DC"'
}

