#!/bin/bash

function del_dc() {
    set_defaults
    run_app $2

    # Wait until a particular message is seen and the cluster dcs exist
    os::cmd::try_until_text 'oc logs dc/"$APP_NAME"' "$1" $((5*minute))
    os::cmd::try_until_success 'oc get dc "$MASTER_DC"' $((2*minute))
    os::cmd::try_until_success 'oc get dc "$WORKER_DC"'

    # Delete the driver dc
    os::cmd::expect_success 'oc delete dc/"$APP_NAME"'
    os::cmd::try_until_failure 'oc get dc/"$APP_NAME"'

    # Check for the master and worker dcs, they should be gone and won't reappear
    os::cmd::try_until_failure 'oc get dc "$MASTER_DC"'
    os::cmd::try_until_failure 'oc get dc "$WORKER_DC"'
}

