#!/bin/bash -e
if [ -f $SPARK_HOME/bin/spark-submit ]; then
cat <<EOF
This is a radanalytics-scala-spark S2I builder image.

For information on how to get started building and running Apache Spark
applications in OpenShift with radanalytics, visit https://radanalytics.io
EOF

else
cat <<EOF
This is an incomplete radanalytics-scala-spark S2I builder image. It is missing
an Apache Spark distribution.

For information on how to get started building and running Apache Spark
applications in OpenShift with radanalytics, visit https://radanalytics.io

For information on how to generate a completed image which does contain
a Spark distribution, read on.

Completing the image
---------------------

To produce a complete radanalytics-scala-spark S2I image, a source-to-image build
must be performed which takes a Spark distribution as input. This can be done in
OpenShift or locally using the s2i tool if it's installed.

Build inputs:
-------------

The OpenShift method can take either local files or a URL as build input.
For the s2i method, local files are required. Here is an example which
downloads an Apache Spark distribution to a local 'build_input' directory
(including the md5 file is optional).

$ mkdir build_input
$ wget https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz -O build_input/spark-2.3.0-bin-hadoop2.7.tgz
$ wget https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz.md5 -O build_input/spark-2.3.0-bin-hadoop2.7.tgz.md5

Completing the image with OpenShift:
------------------------------------

Run a binary build specifying the Spark distribution, for example:

$ oc new-build --name=radanalytics-scala-spark --docker-image=radanalyticsio/radanalytics-scala-spark-inc --binary
$ oc start-build radanalytics-scala-spark --from-file=https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz

This will write the completed image to an imagestream called 'radanalytics-scala-spark'
in the current project. Note that the value of --from-file can also be a local
directory (see Build Inputs above).

Completing the image with the s2i tool:
---------------------------------------

s2i build build_input radanalyticsio/radanalytics-scala-spark-inc radanalytics-scala-spark

This will build a local image named 'radanalytics-scala-spark:latest' which can then
be uploaded to an image repository.
EOF
fi
