#!/bin/sh

set -e

function last_assemble {
    ls -1 | grep -o "^[0-9]*" | tail -1
}

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

set +e
pip show numpy
res=$?
set -e
if [ "$res" -ne 0 ]
then
    if [ -f /opt/app-root/etc/scl_enable ]
    then
        source /opt/app-root/etc/scl_enable && pip install numpy
    else
        pip install numpy
    fi
fi

cp $ADDED_DIR/s2i/run $STI_SCRIPTS_PATH
cp $ADDED_DIR/s2i/usage $STI_SCRIPTS_PATH

pushd $STI_SCRIPTS_PATH
# Find the last file, interpret as base 10 so leading zeroes
# aren't an issue. Add 1 to it and print it in a field of 3.
# This will our added assemble for python that deals with
# dependencies listed in worker-requirements.txt
new=$(printf "%03d" $((10#$(last_assemble)+1)))
popd

cp $ADDED_DIR/s2i/assemble $STI_SCRIPTS_PATH/$new-assemble
