#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added

set +e
pip show numpy
res=$?
set -e
if [ "$res" -ne 0 ]
then
    if [ -f /opt/app-root/etc/scl_enable ]
    then
        source /opt/app-root/etc/scl_enable && pip install numpy
    else
        pip install numpy
    fi
fi

mkdir -p /usr/libexec/s2i
mv /usr/libexec/s2i/assemble /usr/libexec/s2i/assemble.orig
cp -r $ADDED_DIR/s2i/* /usr/libexec/s2i
chown -R 185:0 -R $APP_ROOT && chmod a+rwX -R $APP_ROOT
