package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/redhatanalytics/oshinko-rest/models"
)

// NewUpdateSingleClusterParams creates a new UpdateSingleClusterParams object
// with the default values initialized.
func NewUpdateSingleClusterParams() *UpdateSingleClusterParams {
	var ()
	return &UpdateSingleClusterParams{}
}

/*UpdateSingleClusterParams contains all the parameters to send to the API endpoint
for the update single cluster operation typically these are written to a http.Request
*/
type UpdateSingleClusterParams struct {

	/*Cluster
	  Requested cluster update

	*/
	Cluster *models.NewCluster
	/*Name
	  Name of the cluster

	*/
	Name string
}

// WithCluster adds the cluster to the update single cluster params
func (o *UpdateSingleClusterParams) WithCluster(Cluster *models.NewCluster) *UpdateSingleClusterParams {
	o.Cluster = Cluster
	return o
}

// WithName adds the name to the update single cluster params
func (o *UpdateSingleClusterParams) WithName(Name string) *UpdateSingleClusterParams {
	o.Name = Name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSingleClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Cluster == nil {
		o.Cluster = new(models.NewCluster)
	}

	if err := r.SetBodyParam(o.Cluster); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
