#!/bin/sh

set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR=${SCRIPT_DIR}/added
ARTIFACTS_DIR=/tmp/artifacts

scala_fullname=$(find $ARTIFACTS_DIR -name scala-[0-9.]*\.tgz)
bash -x $SCRIPT_DIR/check_for_download_scala $scala_fullname
cp $scala_fullname /opt

sbt_fullname=$(find $ARTIFACTS_DIR -name sbt-[0-9.]*\.tgz)
bash -x $SCRIPT_DIR/check_for_download_sbt $sbt_fullname
cp $sbt_fullname /opt

pushd /opt
tar -zxf $(basename $scala_fullname)
ln -s $(basename $scala_fullname .tgz) scala

tar -zxf $(basename $sbt_fullname)
sbt_version=$(echo $(basename $sbt_fullname .tgz) | cut -d '-' -f2)
ln -s sbt-launcher-packaging-$sbt_version sbt
popd

/opt/sbt/bin/sbt

mkdir -p /usr/local/s2i
cp -r $ADDED_DIR/s2i/* /usr/local/s2i
chmod a+x /usr/local/s2i/*
chown -R 185:0 $APP_ROOT && chmod a+rwX -R $APP_ROOT
chown -R 185:0 /opt/spark/conf && chmod g+rw -R /opt/spark/conf
chown -R 185:0 /opt/sbt/conf && chmod g+rw -R /opt/sbt/conf
chown -R 185:0 /tmp/.ivy2 && chmod g+rw -R /tmp/.ivy2
chown -R 185:0 /tmp/.sbt && chmod g+rw -R /tmp/.sbt
if [ -f /home/jboss ]; then
    chmod -R g+rwX /home/jboss
fi
